/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  images: {
    minimumCacheTTL: 60,
    domains: ['admin.gobank.com.br', 'localhost'],
  },
  async redirects() {
    return [
      { source: '/about', destination: '/', permanent: true },
      { source: '/site/para-voce', destination: '/abra-sua-conta', permanent: true },
      { source: '/site/para-sua-empresa', destination: '/abra-sua-conta', permanent: true },
      { source: '/site/seja-um-parceiro', destination: '/seja-um-parceiro', permanent: true },
      { source: '/site/sobre-a-go-bank', destination: '/sobre-o-gocapital', permanent: true },
      { source: '/site/fale-com-a-go-bank', destination: '/converse-com-o-gocapital', permanent: true },
      { source: '/site/gohelp', destination: '/central-de-ajuda', permanent: true },
      { source: '/site/creditos-sem-garantia', destination: '/credito-descomplicado', permanent: true },
      { source: '/site/emprestimo-para-padarias', destination: '/credito-descomplicado', permanent: true },
      { source: '/site/emprestimo-para-esteticas', destination: '/credito-descomplicado', permanent: true },
      { source: '/site/emprestimo-para-oficinas-mecanicas', destination: '/credito-descomplicado', permanent: true },
      { source: '/site/emprestimo-para-restaurantes-e-hamburgueres', destination: '/credito-descomplicado', permanent: true },
      { source: '/site/emprestimo-para-maquinas-industriais', destination: '/credito-descomplicado', permanent: true },
      { source: '/site/depoimentos', destination: '/sobre-o-gocapital', permanent: true },
      { source: '/site/blog-da-go-bank', destination: '/blog', permanent: true },
      { source: '/site/emprestimo-para-pmes', destination: '/credito-descomplicado', permanent: true },
      { source: '/site/politica-de-privacidade', destination: '/politica-de-privacidade', permanent: true },
      { source: '/site/wp-content/uploads/2023/01/Termo-de-Uso-de-Conta-de-Pagamento-GO-BANK-2.pdf', destination: '/termos-de-uso', permanent: true },
      { source: '/site/pronampe', destination: '/blog/', permanent: true },
      { source: '/site/selic-a-225-onde-investir', destination: '/blog/', permanent: true },
      { source: '/site/como-controlar-as-contas-de-uma-pequena-empresa', destination: '/blog/', permanent: true },
      { source: '/site/emprestimo-com-garantia-de-veiculo-go-bank', destination: '/blog/', permanent: true },
      { source: '/site/segurogobank', destination: '/seguros-e-consorcios', permanent: true },
      { source: '/site/credito-consignado', destination: '/credito-descomplicado', permanent: true },
      { source: '/contratar/index', destination: '/credito-descomplicado', permanent: true },
      { source: '/site/feed', destination: '/', permanent: true },
      { source: '/categorias/dicas', destination: '/blog', permanent: true },
      { source: '/simule', destination: '/credito-descomplicado', permanent: true },
      { source: '/go-pag', destination: '/maquininhas-go-pag', permanent: true },
      { source: '/quem-somos', destination: '/sobre-o-gocapital', permanent: true },
      { source: '/solucoes-financeiras', destination: '/abra-sua-conta', permanent: true },
      { source: '/consorcio', destination: '/seguros-e-consorcios', permanent: true },
      { source: '/credito', destination: '/credito-descomplicado', permanent: true },
      { source: '/contato', destination: '/converse-com-o-gocapital', permanent: true },
      { source: '/maquininhas', destination: '/maquininhas-go-pag', permanent: true },
      { source: '/sobre-o-gobank', destination: '/sobre-o-gocapital', permanent: true },
      { source: '/sobre-o-go-bank', destination: '/sobre-o-gocapital', permanent: true },
      { source: '/converse-com-o-go-bank', destination: '/converse-com-o-gocapital', permanent: true },
      { source: '/agradecimento-converse-com-a-go-bank', destination: '/agradecimento-converse-com-a-gocapital', permanent: true },
      { source: '/credito-facilitado', destination: '/credito-descomplicado', permanent: true },
      { source: '/blog/selic-a-225-onde-investir', destination: '/blog', permanent: true },
    ];
  },
};

module.exports = nextConfig;
